### ISSUE TITLE
Not able to run count(*) using hive inside the container

### ISSUE THREAD

**Issue by Kalyan-D** [romans-weapon/spear-framework#7]
When I try to run a insert query or a select count(*) in hive which is an MR job the query is getting hung after a point. Below is the snippet.

```
hive> insert into test.counttest values(1,'Abc');
WARNING: Hive-on-MR is deprecated in Hive 2 and may not be available in the future versions. Consider using a different execution engine (i.e. spark, tez) or using Hive 1.X releases.
Query ID = root_20210531084134_915c8e72-1586-406a-8505-01af984ef376
Total jobs = 3
Launching Job 1 out of 3
Number of reduce tasks is set to 0 since there's no reduce operator
```

But I am able to execute a simple select query i am getting the output without any issues.

**Comment by AnudeepKonaboina** [comment]
The container does not have yarn installed for executing map reduce queries using hive. You need to run that by setting the below  param before running your query
``set mapreduce.framework.name=local; //default value is yarn
``
Using this you can execute your query by running mr job locally without use of yarn.

This issue is fixed in the latest commit where the setting has been added to mapredsite.xml file and reinstalling the whole setup will resolve your issue and also new release will be made for the same.
